//move_options = [0, 1, 2];
move_directions = [0, 90, 180, 270];
move_weights = [50, 5, 0]; //move random, stay still, attack
current_move = 0;
move_dir = 0;
move_opt = 0;
move_rnd = 0;
//dir_change = 1;
//dir_wait = 0;
alarm[0] = irandom_range(move_timer - move_timer_rnd, move_timer + move_timer_rnd);
